---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  tasks: 
    - name: Display Register value
      win_shell:  get-service | select name,status | convertto-json -depth 1
      register: servicenamevar
      #when: ansible_distribution == "Microsoft Windows Server Datacenter" # you can use 'and' / 'or' keywork for multiple condition 

    - name: Show output
      debug:
        var: "{{ item | dict2items}}"
        loop: servicenamevar.stdout
      

# You can use below way as well
#when: 
 #       - ansible_distribution == "CentOS" 
  #      - ansible_distribution_major_version | int >= 7

...
