---
-
  hosts: 
    all
  vars_files:
    - servicename.yml
  tasks: 
    - name: jinja services template
      win_service:
        - {% for name== BITS %}
             state==started
          {% endfor %}          
...                   