---
-
  hosts: 
    all
  vars_files:
    - servicename.yml
  tasks: 
    - name: jinja services template
      win_service:
         {% for name== {{servicenames[0]}} %}
                   state==started
         {% for name== {{servicenames[1]}} %}
                   state==stopped          
         {% for name== {{servicenames[2]}} %}
                   state==started
         {% endfor %}          
...                   