---
-
  hosts: 
    all
  tasks: 
    - name: jinja services template
      win_service:
         {% for name== BITS %}
             state==started
         {% endfor %}          
...                   