---
-
  hosts: 
    all
  vars_files:
    - servicename.yml
  tasks: 
    - name: jinja services template
      win_service:
        msg: >
            The task has done 
             {% for name == {{servicenames[0]}}  -%}
                   state == stopped
             {% endfor -%}        
...