---
-
  hosts: 
    all
  vars_files:
    - servicename.yml
  tasks: 
   - name: test Jinja if
      debug:
        msg: >
            This is test if ansible
             {% for ipv4 in ansible_all_ipv4_adrdesses -%}
                   IP Address entry {{ loop.index }} = {{ ipv4 }}
             {% endfor -%}        
...                   