---
-
  hosts: 
    all
  vars_files:
    - servicename.yml
  tasks: 
    - name: Start service BITS if not started
      win_service: 
        name: "{{item}}"
        state: stopped
      loop:
        {{servicenames}}
...
