---
-
  hosts: 
    all
  vars_files:
    - servicename.yml
  tasks: 
    - name: Start service BITS if not started
      win_service: 
      {% for winservice in win_service -%}
        service {{loop.index}} = {{winservice}}
       {% endfor -%}

    


  This is test if ansible
             {% if win_service == "BITS" -%}
                   state=stopped

             {% elif win_service == "spool" -%}
                   state=start
             {% else win_service == "wuauserv" -%}
                   state=start
             {% endif %}


...