---
-
  hosts: 
    all
  vars_files:
    - servicename.yml
  tasks: 
    - name: Start service BITS if not started
      win_service: >
       name: 
         {% for name == "{{servicenames[0]}}" -%}
              state= stopped
         {% for name == "{{servicenames[1]}}" -%}         
              state= started
         {% for name == "{{servicenames[2]}}" -%}
              state= stopped  
         {% endfor -%}         
...